name: Serenity BDD Tests with Tags

on:
  workflow_dispatch: # Esto habilita el botón de "Run workflow" con opciones
    inputs:
      tags:
        description: 'Selecciona el Tag de Cucumber a ejecutar'
        required: true
        default: '@Regresion'
        type: choice
        options:
          - '@loginThePage'
          - '@Smoke'
          - '@Regresion'
          - '@Carrito'
          - '@All'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17 # O la versión que uses (11 o 21)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Serenity Tests
        env:
          # Aquí pasas las credenciales de tu InfluxDB si son dinámicas
          INFLUX_URL: ${{ secrets.INFLUX_URL }}
        run: |
          if [ "${{ github.event.inputs.tags }}" == "@All" ]; then
            mvn clean verify
          else
            mvn clean verify -Dcucumber.filter.tags="${{ github.event.inputs.tags }}"
          fi

      - name: Upload Serenity Reports
        if: always() # Se ejecuta aunque los tests fallen
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report
          path: target/site/serenity